// ui/src/views/Login.tsx
import { ElForm, ElInput, type FormInstance } from 'element-plus'
import { defineComponent, reactive, ref } from 'vue'
import { z } from 'zod'
import { RouterLink } from 'vue-router'
import { t } from '@/i18n'
import { useVocabStore } from '@/store/useVocab'
import { inputNameSchema, inputPasswordSchema } from '@/utils/validation'
import { createSignal } from '@/composables/utilities'
import type { FormRules } from '@/types/forms'

export const Login = defineComponent(() => {
  const store = useVocabStore()
  const ruleFormRef = ref<FormInstance>()
  const ruleForm = reactive({
    username: '',
    password: '',
  })
  const rules: FormRules<typeof ruleForm> = reactive({
    username: [
      {
        required: true,
        validator(rule, username: string | number, callback) {
          try {
            inputNameSchema.parse(String(username).trim())
          } catch (err) {
            if (err instanceof z.ZodError) return callback(new Error(err.issues[0].message))
          }
          callback()
        },
        trigger: 'blur',
      }
    ],
    password: [
      {
        required: true,
        validator(rule, password: string | number, callback) {
          try {
            inputPasswordSchema.parse(String(password))
          } catch (err) {
            if (err instanceof z.ZodError) return callback(new Error(err.issues[0].message))
          }
          callback()
        },
        trigger: 'blur',
      }
    ],
  })
  const [errorMsg, setErrorMsg] = createSignal('')

  function submitForm(ev: Event) {
    ev.preventDefault()
    const formEl = ruleFormRef.value
    if (!formEl) return
    formEl.validate()
      .then(async () => {
        if (!await store.login(ruleForm)) {
          setErrorMsg(t('incorrectUserPassword'))
        }
      })
      .catch(console.error)
  }

  return () => (
    <div class="flex flex-row">
      <div class="mx-auto py-6">
        <section class="py-5">
          <div class="mx-auto flex flex-col items-center justify-center px-6 py-8 lg:py-0">
            <div class="w-full rounded-lg bg-white shadow dark:border sm:max-w-md md:mt-0 xl:p-0">
              <div class="max-w-80 space-y-4 p-6 sm:p-8 md:w-80 md:space-y-6">
                <h1 class="text-xl/tight font-bold tracking-tight text-gray-900 md:text-2xl">
                  {t('login')}
                </h1>
                <ElForm
                  ref={ruleFormRef}
                  model={ruleForm}
                  rules={rules}
                  label-position="top"
                  label-width="100px"
                  class="[&>.el-form-item_label]:font-bold"
                  status-icon
                >
                  <ElForm.FormItem
                    label={t('Name')}
                    prop="username"
                    error={errorMsg()}
                  >
                    <ElInput
                      v-model={ruleForm.username}
                      class="!text-base md:!text-xs"
                    />
                  </ElForm.FormItem>
                  <ElForm.FormItem
                    label={t('Password')}
                    prop="password"
                  >
                    <ElInput
                      v-model={ruleForm.password}
                      type="password"
                      autocomplete="off"
                      class="!text-base md:!text-xs"
                    />
                  </ElForm.FormItem>
                  <div class="flex flex-row gap-2">
                    <button
                      class="box-border flex cursor-pointer items-center rounded-md border border-solid border-transparent bg-[hsl(206,100%,52%)] px-3 py-2 text-sm/3 text-white hover:bg-[hsl(206,100%,40%)]"
                      style="box-shadow: inset 0 1px 0 0 hsl(0deg 0% 100% / 40%);"
                      onClick={submitForm}
                    >
                      {t('Submit')}
                    </button>
                    <button
                      class="box-border inline-flex h-8 max-h-full grow-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-md border bg-white px-3 py-2.5 text-center align-middle text-sm/3 tracking-wide text-neutral-800 transition-colors hover:border-sky-300 hover:bg-sky-100 hover:text-sky-600"
                      onClick={(ev) => {
                        ev.preventDefault()
                        ruleFormRef.value?.resetFields()
                      }}
                    >
                      {t('Reset')}
                    </button>
                  </div>
                </ElForm>
                <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                  Don't have an account yet?
                  <RouterLink
                    to="/register"
                    class="text-primary-600 dark:text-primary-500 font-medium hover:underline"
                  >
                    {` ${t('signup')}`}
                  </RouterLink>
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
})

// ui/src/app/login/page.tsx
import { useForm } from 'react-hook-form'
import { useState } from 'react'
import { Icon } from '@iconify/react'
import type { LoginResponse } from '@/types/shared.ts'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { router } from '@/router'
import { postRequest } from '@/lib/request.ts'
import { type Credential } from '@/api/user.ts'
import { useBearStore } from '@/store/useVocab.ts'

type FormValues = {
  username: string
  password: string
}

export default function Login() {
  const form = useForm<FormValues>({
    defaultValues: {
      username: '',
      password: '',
    },
    reValidateMode: 'onSubmit',
  })

  const {
    register, trigger, handleSubmit, formState: { errors }, setError,
  } = form
  const setUsername = useBearStore((state) => state.setUsername)
  const [passwordVisible, setPasswordVisible] = useState(false)
  async function onSubmit(values: FormValues) {
    setPasswordVisible(false)
    try {
      const resAuth = await postRequest<LoginResponse>(`/api/login`, {
        username: values.username,
        password: values.password,
      } satisfies Credential)

      if (resAuth[0]) {
        setUsername(values.username)
        router.navigate('/').catch(console.error)
      } else {
        setError('root.serverError', {
          message: 'The username/password is incorrect.',
        })
        setError('username', {
          message: '',
        })
        setError('password', {
          message: '',
        })
      }
    } catch (e) {
      setError('root.serverError', {
        message: 'Something went wrong, please try again later',
      })
    }
  }

  return (
    <div className="flex flex-row">
      <div className="mx-auto py-6">
        <section className="py-5">
          <div className="mx-auto flex flex-col items-center justify-center px-6 py-8 lg:py-0">
            <div className="w-full rounded-lg bg-white shadow dark:border sm:max-w-md md:mt-0 xl:p-0">
              <div className="max-w-80 space-y-4 p-6 sm:px-8 sm:py-7 md:w-80 md:space-y-6">
                <h1 className="text-xl/tight font-bold text-gray-900 md:text-2xl">
                  Sign in
                </h1>
                <Form {...form}>
                  <form
                    onSubmit={handleSubmit(onSubmit)}
                    className="space-y-4"
                  >
                    <FormField
                      control={form.control}
                      name="username"
                      rules={{
                        required: 'The Username is required.',
                      }}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Username</FormLabel>
                          <FormControl>
                            <Input
                              type="text"
                              autoComplete="username"
                              placeholder=""
                              {...field}
                              {...register('username')}
                              onBlur={() => {
                                if (form.formState.isDirty) {
                                  trigger('username').catch(console.error)
                                }
                              }}
                              className="text-base md:text-sm"
                            />
                          </FormControl>
                          <FormMessage>{errors.username?.message ?? ''}</FormMessage>
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="password"
                      rules={{
                        required: 'The password is required.',
                      }}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Password</FormLabel>
                          <FormControl>
                            <div className="flex items-center gap-1">
                              <Input
                                type={passwordVisible ? 'text' : 'password'}
                                autoComplete="current-password"
                                placeholder=""
                                {...field}
                                {...register('password')}
                                className="text-base md:text-sm"
                              />
                              <Button
                                variant="outline"
                                className="bg-white px-2"
                                aria-checked={passwordVisible}
                                onClick={(e) => {
                                  e.preventDefault()
                                  setPasswordVisible(!passwordVisible)
                                }}
                              >
                                {passwordVisible ? (
                                  <Icon
                                    icon="lucide:eye"
                                    width={18}
                                    className="text-neutral-600"
                                  />
                                ) : (
                                  <Icon
                                    icon="lucide:eye-off"
                                    width={18}
                                    className="text-neutral-600"
                                  />
                                )}
                              </Button>
                            </div>
                          </FormControl>

                        </FormItem>
                      )}
                    />
                    <FormMessage>{errors.root?.serverError.message}</FormMessage>
                    <Button
                      className="mt-8"
                      type="submit"
                    >
                      Sign in
                    </Button>
                  </form>
                </Form>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}
