// ui/src/components/SegmentedControl.tsx
import { defineComponent, ref, watch } from 'vue'
import { useElementBounding, useSessionStorage } from '@vueuse/core'

export const SegmentedControl = Object.assign(defineComponent(<T extends string>(props: {
  value: T
  name: string
  segments: Readonly<{ value: T, label: string }[]>
  onChoose: (value: T) => void
}) => {
  const pill = ref()
  const pillWidth = useSessionStorage(`${props.name}-width`, 0)
  watch(useElementBounding(pill).width, (v) => v !== 0 && (pillWidth.value = v))
  return () => (
    <div class="box-border flex w-full grow-0 !touch-manipulation px-5 pb-2 pt-3 tracking-wide antialiased tap-transparent !overflow-scrolling-touch ffs-['cv08'] [text-rendering:geometricPrecision] [&_*]:box-border">
      <div class="grid w-full select-none auto-cols-[1fr] grid-flow-col overflow-hidden rounded-[9px] bg-[#EFEFF0] p-0.5 outline-none">
        <span
          ref={pill}
          style={{ transform: `translateX(${pillWidth.value * props.segments.findIndex((seg) => seg.value === props.value)}px)` }}
          class="z-10 col-start-1 col-end-auto row-start-1 row-end-auto rounded-[7px] border-[.5px] border-black/[0.04] bg-white shadow-md transition-transform duration-300 ease-[ease] will-change-transform"
        />
        {props.segments.map((item, index) => (
          <div
            key={index}
            class="group relative first-of-type:col-[1] first-of-type:row-[1] first-of-type:shadow-[none] before:[&:first-of-type_label]:opacity-0 after:[&:last-of-type_label]:opacity-0"
          >
            <input
              id={`${props.name}-${item.value}`}
              type="radio" value={item.value}
              checked={item.value === props.value}
              class="group/i peer absolute inset-0 appearance-none opacity-0 outline-none"
              onInput={(ev) => props.onChoose((ev.target as HTMLInputElement).value as T)}
            />
            <label
              for={`${props.name}-${item.value}`}
              class="relative block cursor-pointer bg-transparent text-center before:absolute before:inset-y-[14%] before:left-0 before:w-px before:translate-x-[-.5px] before:rounded-[10px] before:bg-[#8E8E9326] before:transition-[background] before:duration-200 before:ease-[ease] before:will-change-[background] after:absolute after:inset-y-[14%] after:right-0 after:w-px after:translate-x-[.5px] after:rounded-[10px] after:bg-[#8E8E9326] after:transition-[background] after:duration-200 after:ease-[ease] after:will-change-[background] peer-checked:cursor-default before:peer-checked:z-[1] before:peer-checked:bg-[#EFEFF0FF] after:peer-checked:z-[1] after:peer-checked:bg-[#EFEFF0FF] [&_span]:peer-checked:font-medium"
            >
              <span class="relative z-10 flex justify-center text-sm/6 text-black transition-all duration-200 ease-[ease] will-change-transform group-hover:opacity-20 group-focus:opacity-20 group-active:opacity-20 group-[&:checked+label]/i:opacity-100 group-active:group-[&:not(:checked)+label]/i:scale-95">
                {item.label}
              </span>
            </label>
          </div>
        ))}
      </div>
    </div>
  )
}), { props: ['value', 'name', 'segments', 'onChoose'] })

// ui/src/components/ui/segmented-control.tsx
import { cva, type VariantProps } from 'class-variance-authority'

const segmentedControlVariants = cva(
  `grid w-full !touch-manipulation select-none auto-cols-[1fr] grid-flow-col overflow-hidden tracking-wide antialiased outline-none ffs-['cv08'] [text-rendering:geometricPrecision]`,
  {
    variants: {
      variant: {
        default: 'bg-[#EFEFF0] p-0.5 dark:bg-neutral-800/40',
        ghost: 'bg-transparent px-1.5 py-1',
      },
      size: {
        default: '',
        small: '',
        medium: '',
      },
    },
    compoundVariants: [
      {
        variant: 'default',
        className: 'group/default',
      },
      {
        variant: 'ghost',
        className: 'group/ghost',
      },
    ],
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  },
)

interface SegmentedControlProps<T extends string> extends
  HTMLAttributes<HTMLDivElement>,
  RefAttributes<HTMLDivElement>,
  VariantProps<typeof segmentedControlVariants> {
  value: NoInfer<T>
  segments: Readonly<{ value: T, label: string }[]>
  onChoose: (value: T) => void
}

export function SegmentedControl<T extends string>({
  value,
  segments,
  onChoose,
  variant,
  size,
  className,
  ref,
  ...props
}: SegmentedControlProps<T>) {
  const pillRefs = useRef<Partial<Record<T, HTMLSpanElement>>>({})

  function handleOnChange(newValue: T) {
    const pillRef = pillRefs.current[newValue]
    if (pillRef) {
      const previousPill = pillRefs.current[value]
      const domRect = previousPill?.getBoundingClientRect()
      activatePill(pillRef, domRect)
      onChoose(newValue)
    }
  }

  function activatePill(pillRef: HTMLElement, previousIndicatorClientRect?: DOMRect) {
    const element = pillRef

    if (
      !previousIndicatorClientRect
      || !element.getBoundingClientRect
    )
      return

    // https://github.com/angular/components/blob/a7f87a80a18a62d75a8c5621fd89dbc2cf28a865/src/material/tabs/ink-bar.ts#L114
    const currentClientRect = element.getBoundingClientRect()
    const widthDelta = previousIndicatorClientRect.width / currentClientRect.width
    const xPosition = previousIndicatorClientRect.left - currentClientRect.left
    element.style.setProperty(
      'transform',
      `translateX(${xPosition}px) scaleX(${widthDelta})`,
    )
    element.getBoundingClientRect()
    element.style.setProperty('transform', '')
  }

  function addToRefs(key: T) {
    return (el: HTMLDivElement) => {
      pillRefs.current[key] = el
    }
  }

  return (
    <Squircle
      ref={ref}
      squircle={{
        cornerRadius: 9,
      }}
      borderWidth={1}
      className={cn(segmentedControlVariants({ variant, size, className }))}
      {...props}
    >
      {segments.map((item) => (
        <Segment
          key={item.value}
          value={item.value}
          sqRef={addToRefs(item.value)}
          checked={item.value === value}
          label={item.label}
          onValueChange={handleOnChange}
        />
      ))}
    </Squircle>
  )
}

function Segment<T extends string>({
  value,
  label,
  checked,
  onValueChange,
  sqRef,
  className,
  ...props
}: {
  value: T
  label: string
  onValueChange: (value: T) => void
  checked: boolean
  sqRef: Ref<HTMLDivElement>
} & React.HTMLAttributes<HTMLDivElement> & RefAttributes<HTMLDivElement>) {
  const id = useId()
  return (
    <div
      className={cn('group/d relative first-of-type:col-[1] first-of-type:row-[1] first-of-type:shadow-none', className)}
      {...props}
    >
      <input
        id={id}
        aria-label="Segmented control"
        type="radio"
        value={value}
        checked={checked}
        className="group/i peer absolute inset-0 appearance-none opacity-0 outline-none"
        onChange={() => {
          onValueChange(value)
        }}
      />
      <label
        htmlFor={id}
        className="group/l relative block cursor-pointer bg-transparent text-center before:absolute before:inset-y-[14%] before:left-0 before:w-px before:translate-x-[-.5px] before:rounded-[10px] before:bg-neutral-300 before:transition-[background] before:duration-200 before:ease-[ease] before:will-change-[background] group-first-of-type/d:before:opacity-0 group-[:has(:checked)+*]/d:before:bg-transparent peer-checked:cursor-default peer-checked:before:z-10 peer-checked:before:bg-transparent dark:before:bg-slate-700"
      >
        <div className="flex flex-col justify-center text-sm/6 group-[]/ghost:leading-[1.375rem]">
          <div
            className="relative z-10 flex justify-center text-black transition-all duration-200 ease-[ease] will-change-transform group-hover/d:opacity-20 group-focus/d:opacity-20 group-active/d:opacity-20 group-active/d:delay-150 group-active/d:group-[:not(:checked)+label]/i:scale-95 peer-checked:group-[]/l:font-medium peer-checked:group-[]/l:opacity-100 dark:text-white"
          >
            {label}
          </div>
          <div
            title={label}
            className="before:invisible before:block before:h-0 before:overflow-hidden before:font-bold before:content-[attr(title)]"
          />
        </div>
        <div className="absolute left-0 top-0 size-full">
          <Squircle
            ref={sqRef}
            squircle={{
              cornerRadius: 7,
            }}
            borderWidth={0.5}
            className={cn(
              'flex size-full ease-[ease] will-change-transform group-[]/default:peer-checked:group-[]/l:border-0 group-[]/default:peer-checked:group-[]/l:bg-black/[.04] group-[]/ghost:peer-checked:group-[]/l:bg-neutral-200 peer-checked:group-[]/l:bg-white group-[]/default:peer-checked:group-[]/l:shadow group-[]/default:peer-checked:group-[]/l:before:bg-white dark:group-[]/ghost:peer-checked:group-[]/l:bg-slate-600 dark:group-[]/default:peer-checked:group-[]/l:before:bg-neutral-600',
              checked && 'transition-transform duration-300',
            )}
          />
        </div>
      </label>
    </div>
  )
}
