// src/components/Switch.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps({
  state: Boolean,
  text: { type: Array, default: () => ['off', 'on'] },
})
const emit = defineEmits(['toggle'])
const toggleState = ref<boolean>(props.state)
const toggleFilter = () => emit('toggle', toggleState.value)
</script>

<template>
  <div>
    <label class="form-switch flex cursor-pointer justify-center tap-transparent">
      <span class="mx-2.5 flex flex-col-reverse justify-center text-base">{{ text[0] }}</span>
      <input
        v-model="toggleState"
        type="checkbox"
        class="hidden"
        @change="toggleFilter"
      >
      <i class="relative mr-2 inline-block h-[26px] w-[46px] select-none rounded-[23px] bg-[#e6e6e6] align-text-bottom transition-all duration-300 ease-linear" />
      <span class="mx-2.5 flex flex-col-reverse justify-center text-base">{{ text[1] }}</span>
    </label>
  </div>
</template>

<style lang="scss" scoped>
:root {
  --switch-bg-color: #e6e6e6;
}

.form-switch:active {
  i::after {
    width: 28px;
    transform: translate3d(2px, 2px, 0);
  }

  input:checked + i::after {
    transform: translate3d(16px, 2px, 0);
  }
}

i {
  &::before,
  &::after {
    content: '';
    position: absolute;
    left: 0;
    height: 22px;
    border-radius: 11px;
  }

  &::before {
    width: 42px;
    background-color: var(--switch-bg-color);
    transform: translate3d(2px, 2px, 0) scale3d(1, 1, 1);
    transition: all 0.25s linear;
  }

  &::after {
    width: 22px;
    background-color: #fff;
    box-shadow: 0 2px 2px rgba(0, 0, 0, 0.24);
    transform: translate3d(2px, 2px, 0);
    transition: all 0.35s cubic-bezier(.34, .35, .11, 1.19)
  }
}

input:checked + i {
  background-color: rgb(52, 199, 89);

  &::before {
    transform: translate3d(18px, 2px, 0) scale3d(0, 0, 0);
  }

  &::after {
    transform: translate3d(22px, 2px, 0);
  }
}
</style>

// ui/src/components/ui/Switch.tsx
export function Switch({
  checked,
  onChange,
}: {
  checked: boolean
  onChange: (checked: boolean) => void
}) {
  return (
    <div>
      <label className="group/label flex cursor-pointer justify-center [--squircle-circle-smooth:0.14]">
        <input
          checked={checked}
          type="checkbox"
          className="peer hidden"
          onChange={(ev) => {
            onChange(ev.target.checked)
          }}
        />
        <div className="group/d relative inline-block h-[--sw-h] w-[--sw-w] select-none overflow-hidden rounded-[23px] bg-neutral-200 align-text-bottom transition-all duration-300 ease-linear sq-smooth-x-[.14] sq-smooth-y-[.8] sq-radius-full sq-radius-y-[8.4] sq-fill-[red] [--sw-h:26px] [--sw-w:46px] *:absolute *:rounded-full peer-checked:bg-[rgb(52,199,89)] peer-checked:*:right-[18px] sq:rounded-none sq:[mask:paint(squircle)] dark:bg-neutral-700">
          <div className="h-[calc(var(--sw-h)-4px)] w-[calc(var(--sw-w)-4px)] bg-neutral-200 [transform:translate3d(2px,2px,0)_scale3d(1,1,1)] [transition:all_0.25s_linear] peer-checked:group-[]/d:[transform:translate3d(18px,2px,0)_scale3d(0,0,0)] dark:bg-neutral-700" />
          <div className="size-[calc(var(--sw-h)-4px)] bg-white shadow-md sq-smooth-x-[.14] sq-radius-[5] sq-outline-0 sq-fill-white [transform:translate3d(2px,2px,0)] [transition:all_0.35s_cubic-bezier(0.34,0.35,0.11,1.19),width_150ms_ease-in-out] group-hover/label:group-active/label:w-7 group-hover/label:group-active/label:delay-75 peer-checked:group-[]/d:[transform:translate3d(16px,2px,0)] sq:bg-transparent sq:[background:paint(squircle)]" />
        </div>
      </label>
    </div>
  )
}
