// ui/src/components/Footer.tsx
export function Footer() {
  return (
    <footer className="mt-6 w-full bg-zinc-100 dark:bg-zinc-800">
      <div className="mx-auto max-w-screen-xl">
        <section className="px-5 py-3">
          <div className="flex items-center gap-2 text-xs tracking-wide">
            <IconLucideCheckCircle
              className="size-[14px] text-neutral-400"
            />
            <span className="text-neutral-500">SUB VOCAB</span>
          </div>
        </section>
      </div>
    </footer>
  )
}

// src/components/Footer.vue
<script lang="tsx" setup>

</script>

<template>
  <footer class="w-full bg-zinc-100">
    <div class="mx-auto max-w-screen-xl">
      <section class="px-5 py-3">
        <div class="text-xs tracking-wide text-neutral-500">
          Copyright © 2022 Mitchell
        </div>
      </section>
    </div>
  </footer>
</template>
