// ui/src/components/ui/FileInput.tsx
import { defineComponent } from 'vue'
import { v4 as uuidv4 } from 'uuid'
import { twMerge } from 'tailwind-merge'
import { getFileContent } from '@/lib/filesHandler'

export const FileInput = defineComponent((props: {
  onFileInput: (file: {
    value: string
    name: string
  }) => void
  className?: string
}, { slots, expose }) => {
  function onFileChange(ev: Event) {
    const fileList = (ev.target as HTMLInputElement).files
    if (fileList && fileList.length > 0) {
      getFileContent(fileList).then(props.onFileInput).catch(console.error)
    }
  }

  function dropFile(ev: DragEvent) {
    ev.preventDefault()
    const files = ev.dataTransfer?.files
    if (files && files.length > 0) {
      getFileContent(files).then(props.onFileInput).catch(console.error)
    }
  }

  function inputChanged() {
    const input = document.querySelectorAll<HTMLInputElement>('#browseFiles' + id)
    for (let i = 0; i < input.length; i++) {
      input[i].value = ''
    }
  }

  expose({ inputChanged })

  const id = uuidv4()
  return () => (
    <div
      onDrop={dropFile}
      class={twMerge(props.className)}
    >
      <label
        class="box-border inline-flex h-8 max-h-full grow-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-md border bg-white px-3 py-2.5 text-center align-middle text-sm/3 tracking-wide text-neutral-800 transition-colors hover:border-sky-300 hover:bg-sky-100 hover:text-sky-600"
        for={'browseFiles' + id}
      >
        {slots.default?.()}
      </label>
      <input
        id={'browseFiles' + id}
        class="file-input"
        type="file"
        hidden
        multiple
        onChange={onFileChange}
      />
    </div>
  )
})

// ui/src/components/file-input.tsx
import type React from 'react'

import { Button, FileTrigger } from 'react-aria-components'

import { getFileContent, SUPPORTED_FILE_TYPES } from '@/lib/filesHandler'
import { fileTypesAtom, uapAtom } from '@/store/useVocab'

export function FileInput({
  onFileSelect,
  children,
  className = '',
}: {
  onFileSelect: (file: {
    value: string
    name: string
  }) => void
  children: React.ReactNode
  className?: string
}) {
  const { os } = useAtomValue(uapAtom)
  const [fileTypes] = useAtom(fileTypesAtom)
  const fileTypeNames = fileTypes.filter((fileType) => fileType.checked).map((fileType) => fileType.type)
  const acceptedFileTypes = [...SUPPORTED_FILE_TYPES, ...fileTypeNames]

  function handleFileSelect(fileList: FileList | null) {
    if (fileList)
      getFileContent(fileList).then(onFileSelect).catch(console.error)
  }

  function dropFile(ev: React.DragEvent<HTMLDivElement>) {
    ev.preventDefault()
    const files = ev.dataTransfer.files
    if (files)
      getFileContent(files).then(onFileSelect).catch(console.error)
  }

  return (
    <div
      onDrop={dropFile}
      className={className}
    >
      <FileTrigger
        allowsMultiple
        // https://stackoverflow.com/a/47387521/10903455
        // https://caniuse.com/input-file-accept
        {...(os?.name === 'iOS' ? {} : {
          acceptedFileTypes,
        })}
        onSelect={handleFileSelect}
      >
        <Squircle
          squircle={{
            cornerRadius: 7,
          }}
          borderWidth={1}
          className="inline-flex h-8 max-h-full grow-0 cursor-pointer items-center justify-center whitespace-nowrap bg-border px-3 py-2.5 text-center align-middle text-sm/3 tracking-wide transition-colors before:bg-background hover:border-sky-300 hover:bg-sky-100 hover:text-sky-600 focus-visible:!bg-ring focus-visible:outline-0"
          asChild
        >
          <Button>
            { children}
          </Button>
        </Squircle>
      </FileTrigger>
    </div>
  )
}
