// src/views/user/Password.vue
<script lang="ts" setup>
import type { FormInstance, FormItemRule } from 'element-plus'
import { reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElButton, ElForm, ElFormItem, ElInput } from 'element-plus'
import Cookies from 'js-cookie'
import { useUserStore } from '@/store/useState'
import router from '@/router'
import { changePassword, logoutToken } from '@/api/user'
import { useVocabStore } from '@/store/useVocab'
import { resetForm } from '@/utils/elements'

const { t } = useI18n()
const store = useUserStore()
const ruleFormRef = ref<FormInstance>()

function validatePass(rule: FormItemRule | FormItemRule[], value: string, callback: () => void) {
  if (value === '') {
    return callback()
  }

  if (ruleForm.checkPass !== '') {
    if (!ruleFormRef.value) return
    ruleFormRef.value.validateField('checkPass', () => null)
  }

  callback()
}

function validatePass2(rule: FormItemRule | FormItemRule[], value: string, callback: (arg0?: Error) => void) {
  if (value === '' && ruleForm.password === '') {
    return callback()
  }

  if (value !== ruleForm.password) {
    return callback(new Error(t('inputsNotMatch')))
  }

  callback()
}

const ruleForm = reactive({
  oldPassword: '',
  password: '',
  checkPass: '',
})

const rules = reactive({
  password: [{ validator: validatePass, trigger: 'blur' }],
  checkPass: [{ validator: validatePass2, trigger: 'blur' }],
})

function submitForm(formEl: FormInstance | undefined) {
  if (!formEl) return
  formEl.validate((valid) => {
    if (!valid) {
      console.log('error submit!')
      return false
    }

    alterInfo(ruleForm)
  })
}

const errorMsg = ref('')

async function alterInfo(form: typeof ruleForm) {
  if (form.password !== '') {
    form.password = form.password.trim()
    const res = await changePassword({
      username: store.user.name,
      oldPassword: form.oldPassword,
      newPassword: form.password,
    })

    if (res.success) {
      await logOut()
    } else {
      errorMsg.value = res.message || 'something went wrong'
    }
  }
}

const userStore = useUserStore()

async function logOut() {
  await logoutToken({ username: store.user.name })
  Cookies.remove('_user', { path: '' })
  Cookies.remove('acct', { path: '' })
  userStore.user.name = ''
  useVocabStore().resetUserVocab()
  setTimeout(() => {
    router.push('/login')
  }, 0)
}
</script>

<template>
  <div class="flex flex-col">
    <div class="mb-3 border-b pb-1.5 text-xl">
      {{ t('changePassword') }}
    </div>
    <div class="flex w-80">
      <el-form
        ref="ruleFormRef"
        :model="ruleForm"
        :rules="rules"
        label-position="top"
        label-width="100px"
        class="max-w-[460px] [&>.el-form-item_label]:font-bold"
        status-icon
      >
        <el-form-item
          :label="t('Old Password')"
          prop="oldPassword"
          :error="errorMsg"
        >
          <el-input
            v-model="ruleForm.oldPassword"
            type="password"
            autocomplete="off"
            class="!text-base md:!text-xs"
          />
        </el-form-item>
        <el-form-item
          :label="t('New Password')"
          prop="password"
        >
          <el-input
            v-model="ruleForm.password"
            type="password"
            autocomplete="off"
            class="!text-base md:!text-xs"
          />
        </el-form-item>
        <el-form-item
          :label="t('New Password Confirm')"
          prop="checkPass"
        >
          <el-input
            v-model="ruleForm.checkPass"
            type="password"
            autocomplete="off"
            class="!text-base md:!text-xs"
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            @click="submitForm(ruleFormRef)"
          >
            {{ t('Confirm Changes') }}
          </el-button>
          <el-button @click="resetForm(ruleFormRef)">
            {{ t('Reset') }}
          </el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

// ui/src/pages/user/password/page.tsx
import { useForm } from 'react-hook-form'
import { Icon } from '@iconify/react'
import { useState } from 'react'
import Cookies from 'js-cookie'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { router } from '@/router'
import { setUsername, store, useSnapshot } from '@/store/useVocab.ts'
import {
  changePassword, logoutToken,
} from '@/api/user'

type FormValues = {
  oldPassword: string
  newPassword: string
}

export const Password = () => {
  const { t } = useTranslation()
  const { username } = useSnapshot(store)

  function logout() {
    logoutToken({
      username,
    })
      .then(() => {
        Cookies.remove('_user', { path: '' })
        Cookies.remove('acct', { path: '' })
        setUsername('')
        requestAnimationFrame(() => {
          router.navigate('/').catch(console.error)
        })
      })
      .catch(console.error)
  }

  const form = useForm<FormValues>({
    defaultValues: {
      oldPassword: '',
      newPassword: '',
    },
    reValidateMode: 'onSubmit',
  })

  const {
    register, trigger, handleSubmit, formState: { errors }, setError,
  } = form

  const [oldPasswordVisible, setOldPasswordVisible] = useState(false)
  const [newPasswordVisible, setNewPasswordVisible] = useState(false)

  async function onSubmit(values: FormValues) {
    setOldPasswordVisible(false)
    try {
      const res = await changePassword({
        username,
        oldPassword: values.oldPassword,
        newPassword: values.newPassword,
      })

      if (res.success) {
        logout()
      } else {
        setError('root.serverError', {
          message: 'Something went wrong.',
        })
      }
    } catch (e) {
      setError('root.serverError', {
        message: 'Something went wrong, please try again later',
      })
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <div>
        <div className="mb-3 border-b pb-1.5 text-xl">
          {t('changePassword')}
        </div>
        <div className="flex w-80" >
          <Form {...form}>
            <form
              onSubmit={handleSubmit(onSubmit)}
              className="space-y-4"
            >
              <FormField
                control={form.control}
                name="oldPassword"
                rules={{
                  required: 'The password is required.',
                }}
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('Old Password')}</FormLabel>
                    <FormControl>
                      <div className="flex items-center gap-1">
                        <Input
                          type={oldPasswordVisible ? 'text' : 'password'}
                          autoComplete="current-password"
                          placeholder=""
                          {...field}
                          {...register('oldPassword')}
                          className="text-base md:text-sm"
                        />
                        <Button
                          variant="outline"
                          className="bg-white px-2"
                          aria-checked={oldPasswordVisible}
                          onClick={(e) => {
                            e.preventDefault()
                            setOldPasswordVisible(!oldPasswordVisible)
                          }}
                        >
                          {oldPasswordVisible ? (
                            <Icon
                              icon="lucide:eye"
                              width={18}
                              className="text-neutral-600"
                            />
                          ) : (
                            <Icon
                              icon="lucide:eye-off"
                              width={18}
                              className="text-neutral-600"
                            />
                          )}
                        </Button>
                      </div>
                    </FormControl>
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="newPassword"
                rules={{
                  required: 'The password is required.',
                  minLength: { value: 8, message: 'The password must be at least 8 characters.' },
                }}
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('New Password')}</FormLabel>
                    <FormControl>
                      <div className="flex items-center gap-1">
                        <Input
                          type={newPasswordVisible ? 'text' : 'password'}
                          autoComplete="new-password"
                          placeholder=""
                          {...field}
                          {...register('newPassword')}
                          className="text-base md:text-sm"
                        />
                        <Button
                          variant="outline"
                          className="bg-white px-2"
                          aria-checked={newPasswordVisible}
                          onClick={(e) => {
                            e.preventDefault()
                            setNewPasswordVisible(!newPasswordVisible)
                          }}
                        >
                          {newPasswordVisible ? (
                            <Icon
                              icon="lucide:eye"
                              width={18}
                              className="text-neutral-600"
                            />
                          ) : (
                            <Icon
                              icon="lucide:eye-off"
                              width={18}
                              className="text-neutral-600"
                            />
                          )}
                        </Button>
                      </div>
                    </FormControl>
                    <FormMessage>{errors.newPassword?.message ?? ''}</FormMessage>
                  </FormItem>
                )}
              />
              <FormMessage>{errors.root?.serverError.message}</FormMessage>
              <Button
                className="mt-8"
                type="submit"
              >
                {t('Confirm Changes')}
              </Button>
            </form>
          </Form>
        </div>
      </div>
    </div>
  )
}
