// ui/src/pages/register/page.tsx
import { useForm } from 'react-hook-form'
import { Icon } from '@iconify/react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { router } from '@/router'
import { isUsernameTaken, register as signUp } from '@/api/user'

type FormValues = {
  username: string
  password: string
}

export function SignUp() {
  const form = useForm<FormValues>({
    defaultValues: {
      username: '',
      password: '',
    },
    reValidateMode: 'onSubmit',
  })

  const {
    register, trigger, handleSubmit, formState: { errors }, setError,
  } = form

  const [passwordVisible, setPasswordVisible] = useState(false)

  async function onSubmit(values: FormValues) {
    setPasswordVisible(false)
    try {
      const usernameTaken = await isUsernameTaken({
        username: values.username,
      })
      if (usernameTaken.has) {
        setError('username', {
          message: 'The username is taken.',
        })
        return
      }

      const resAuth = await signUp({
        username: values.username,
        password: values.password,
      })

      if (resAuth[0].result === 1) {
        router.navigate('/login').catch(console.error)
      } else {
        setError('root.serverError', {
          message: 'Something went wrong, please try again later',
        })
      }
    } catch (e) {
      setError('root.serverError', {
        message: 'Something went wrong, please try again later',
      })
    }
  }

  return (
    <div className="flex flex-row">
      <div className="mx-auto py-6">
        <section className="py-5">
          <div className="mx-auto flex flex-col items-center justify-center px-6 py-8 lg:py-0">
            <div className="w-full rounded-lg bg-white shadow dark:border sm:max-w-md md:mt-0 xl:p-0">
              <div className="max-w-80 space-y-4 p-6 sm:px-8 sm:py-7 md:w-80 md:space-y-6">
                <h1 className="text-xl/tight font-bold text-gray-900 md:text-2xl">
                  Sign Up
                </h1>
                <Form {...form}>
                  <form
                    onSubmit={handleSubmit(onSubmit)}
                    className="space-y-4"
                  >
                    <FormField
                      control={form.control}
                      name="username"
                      rules={{
                        required: 'The Username is required.',
                        minLength: { value: 3, message: 'The Username must be at least 3 characters.' },
                      }}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Username</FormLabel>
                          <FormControl>
                            <Input
                              type="text"
                              placeholder=""
                              autoComplete="username"
                              {...field}
                              {...register('username')}
                              onBlur={() => {
                                if (form.formState.isDirty) {
                                  trigger('username').catch(console.error)
                                }
                              }}
                              className="text-base md:text-sm"
                            />
                          </FormControl>
                          <FormMessage>{errors.username?.message ?? ''}</FormMessage>
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="password"
                      rules={{
                        required: 'The password is required.',
                        minLength: { value: 8, message: 'The password must be at least 8 characters.' },
                      }}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Password</FormLabel>
                          <FormControl>
                            <div className="flex items-center gap-1">
                              <Input
                                type={passwordVisible ? 'text' : 'password'}
                                autoComplete="new-password"
                                placeholder=""
                                {...field}
                                {...register('password')}
                                className="text-base md:text-sm"
                              />
                              <Button
                                variant="outline"
                                className="bg-white px-2"
                                aria-checked={passwordVisible}
                                onClick={(e) => {
                                  e.preventDefault()
                                  setPasswordVisible(!passwordVisible)
                                }}
                              >
                                {passwordVisible ? (
                                  <Icon
                                    icon="lucide:eye"
                                    width={18}
                                    className="text-neutral-600"
                                  />
                                ) : (
                                  <Icon
                                    icon="lucide:eye-off"
                                    width={18}
                                    className="text-neutral-600"
                                  />
                                )}
                              </Button>
                            </div>
                          </FormControl>
                          <FormMessage>{errors.password?.message ?? ''}</FormMessage>
                        </FormItem>
                      )}
                    />
                    <FormMessage>{errors.root?.serverError.message}</FormMessage>
                    <Button
                      className="mt-8"
                      type="submit"
                    >
                      Create account
                    </Button>
                  </form>
                </Form>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}

// ui/src/views/Register.tsx
import type { FormInstance } from 'element-plus'
import { ElButton, ElForm, ElFormItem, ElInput } from 'element-plus'
import { defineComponent, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { z } from 'zod'
import { t } from '@/i18n'
import router from '@/router'
import { isUsernameTaken, register } from '@/api/user'
import { inputPasswordSchema, usernameSchema } from '@/utils/validation'
import { createSignal } from '@/composables/utilities'
import type { FormRules } from '@/types/forms'

export const Register = defineComponent(() => {
  const ruleFormRef = ref<FormInstance>()
  const ruleForm = reactive({
    username: '',
    password: '',
    checkPass: '',
  })
  const rules: FormRules<typeof ruleForm> = reactive({
    username: [
      {
        required: true,
        async asyncValidator(rule, username: string, callback) {
          try {
            usernameSchema.parse(String(username))
          } catch (err) {
            if (err instanceof z.ZodError) return callback(new Error(err.issues[0].message))
          }

          if ((await isUsernameTaken({ username })).has) {
            return callback(new Error(`${username} ${t('alreadyTaken')}`))
          }
          callback()
        },
        trigger: 'blur',
      }
    ],
    password: [
      {
        required: true,
        validator(rule, value: string, callback) {
          try {
            inputPasswordSchema.parse(String(value))
          } catch (err) {
            if (err instanceof z.ZodError) return callback(new Error(err.issues[0].message))
          }

          if (ruleForm.checkPass !== '') {
            if (!ruleFormRef.value) return
            ruleFormRef.value.validateField('checkPass', () => null).catch(console.error)
          }

          callback()
        },
        trigger: 'blur',
      }
    ],
    checkPass: [
      {
        required: true,
        validator(rule, value: string, callback) {
          if (value === '') {
            return callback(new Error(t('Please input the password again')))
          }

          if (value !== ruleForm.password) {
            return callback(new Error(t('inputsNotMatch')))
          }

          callback()
        },
        trigger: 'blur',
      }
    ],
  })
  const [errorMsg, setErrorMsg] = createSignal('')

  function submitForm() {
    const formEl = ruleFormRef.value
    if (!formEl) return
    formEl.validate()
      .then(async () => {
        if ((await register(ruleForm))[0].result === 1) {
          router.push('/login').catch(console.error)
        } else {
          setErrorMsg('Something went wrong.')
        }
      })
      .catch(console.error)
  }

  return () => (
    <div class="flex flex-row">
      <div class="mx-auto py-6">
        <section class="py-5">
          <div class="mx-auto flex flex-col items-center justify-center px-6 lg:py-0">
            <div class="w-full rounded-lg bg-white shadow dark:border sm:max-w-md md:mt-0 xl:p-0">
              <div class="max-w-80 space-y-4 p-6 sm:p-8 md:w-80 md:space-y-6">
                <h1 class="text-xl/tight font-bold tracking-tight text-gray-900 md:text-2xl">
                  {t('signup')}
                </h1>
                <ElForm
                  ref={ruleFormRef}
                  model={ruleForm}
                  rules={rules}
                  label-position="top"
                  label-width="100px"
                  class="[&>.el-form-item_label]:font-bold"
                  status-icon
                >
                  <ElFormItem
                    label={t('Name')}
                    prop="username"
                    error={errorMsg()}
                  >
                    <ElInput
                      v-model={ruleForm.username}
                      class="!text-base md:!text-xs"
                    />
                  </ElFormItem>
                  <ElFormItem
                    label={t('Password')}
                    prop="password"
                  >
                    <ElInput
                      v-model={ruleForm.password}
                      type="password"
                      autocomplete="off"
                      class="!text-base md:!text-xs"
                    />
                  </ElFormItem>
                  <ElFormItem
                    label={t('Confirm')}
                    prop="checkPass"
                  >
                    <ElInput
                      v-model={ruleForm.checkPass}
                      type="password"
                      autocomplete="off"
                      class="!text-base md:!text-xs"
                    />
                  </ElFormItem>
                  <ElFormItem>
                    <ElButton
                      type="primary"
                      onClick={submitForm}
                    >
                      {t('Create Account')}
                    </ElButton>
                    <ElButton onClick={() => ruleFormRef.value?.resetFields()}>
                      {t('Reset')}
                    </ElButton>
                  </ElFormItem>
                </ElForm>
                <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                  Already have an account?
                  <RouterLink
                    to="/login"
                    class="text-primary-600 dark:text-primary-500 font-medium hover:underline"
                  >
                    {` ${t('login')}`}
                  </RouterLink>
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
})
